services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.api 
    container_name: emd-api 
    expose:
      - "8000"
    environment:
      - ENV=production
      - LOG_LEVEL=info
      - HOST=0.0.0.0
      - PORT=8000
    networks:
      - emd-network 
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./ui/
      dockerfile: Dockerfile.ui
    container_name: emd-frontend 
    expose:
     - "8501"
    environment:
      - API_BASE_URL=/api
    depends_on:
      api:
        condition: service_healthy
    networks:
      - emd-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: emd-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      api:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - emd-network
    restart: unless-stopped

networks:
  emd-network:
    driver: bridge