[project]
name = "emd-traiding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "emd-signal>=1.6.4",
    "logger>=1.4",
    "pandas>=2.2.3",
    "pandas-ta>=0.3.14b0",
    "price_loaders"
]
